<?php
$shopId=addslashes($this->helper('Cocote\Feed\Helper\Data')->getConfigValue('cocote/general/shop_id'));
?>
<?php if($shopId): ?>
    <script src="https://js.cocote.com/script-fr.min.js"></script>
    <script type="text/javascript">
    new CocoteTSA({
        lang: "fr",
        mSiteId: "<?php echo $shopId; ?>"
    });

    function writeCookie(cookieName, cookieValue, expires, domain,
                         path, secureFlag) {
        if (cookieName) {
            var cookieDetails = cookieName + "=" +
                escape(cookieValue);

            cookieDetails += (expires ? "; expires=" +
                expires.toGMTString(): '');

            cookieDetails += (domain ? "; domain=" + domain: '');
            cookieDetails += (path ? "; path=" + path: '');
            cookieDetails += (secureFlag ? "; secure": '');
            document.cookie = cookieDetails;
        }
    }

    var url_string = window.location.href;
    var url = new URL(url_string);
    var token = url.searchParams.get("cocotecashbacktoken");
    if (token) {
        var expiredDate = new Date();
        expiredDate.setHours(+24);
        writeCookie('Cocote-token',token,expiredDate,'','/','');
    }

</script>
<?php endif; ?>